server:
  port: 8888
spring:
  data:
    mongodb:
      uri: mongodb://onegene:onegene100@mongo.dev.1genehealth.com:27017/old_report
#      uri: mongodb://127.0.0.1:27017/test

redisson:
  uri: redis://:bto100@101.37.146.32:6379
  database: 2
#  uri: redis://:root123456@www.booleandev.xyz:6379
#  database: 1



